src/app/pastanaga-login/pastanaga-login.component.html
Fixing this:  I renamed the method but forgot to update the event handler name.
=> Call the intended method on click event.

package-lock.json, package.json
fixing cannot find module error
=> fix : Error: Cannot find module webpack/lib/node/NodeTemplatePlugin

projects/pastanaga-angular/src/lib/avatar/avatar.component.ts, projects/pastanaga-angular/src/lib/styles/_grid.scss
added imageSrc input to avatar component and convenient class in grid
=> added imageSrc to avatar, added self-end class to grid

projects/pastanaga-angular/src/lib/controls/toggles/toggle/toggle.component.html, projects/pastanaga-angular/src/lib/controls/toggles/toggle/toggle.component.spec.ts, projects/pastanaga-angular/src/lib/controls/toggles/toggle/toggle.component.ts
=> toggle component tests and fixes

CHANGELOG.md, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/controls/form-field.model.ts, projects/pastanaga-angular/src/lib/controls/textfield/input/input.component.ts, projects/pastanaga-angular/src/lib/styles/_textfields.scss, projects/pastanaga-angular/src/lib/styles/theme/_textfield.scss
I also added an enum that can help choose proper input name 
or let's us find out if "name" attribute is going to be autofilled properly or not by browsers.
=> updated form-fields styling when autofilled

CHANGELOG.md, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/styles/_toast.scss, projects/pastanaga-angular/src/lib/toast/toast.component.html, projects/pastanaga-angular/src/lib/toast/toast.component.scss, projects/pastanaga-angular/src/lib/toast/toast.component.spec.ts, projects/pastanaga-angular/src/lib/toast/toast.component.ts
[ch29520]
--Change to animate in/out from top
--3s Pause Default, with 5s on Toasts w/ Buttons
--Component test
=> Toast Styling Updates

CHANGELOG.md, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/button/button.component.html, projects/pastanaga-angular/src/lib/button/button.module.ts, projects/pastanaga-angular/src/lib/controls/toggles/checkbox/checkbox.component.html, projects/pastanaga-angular/src/lib/controls/toggles/checkbox/checkbox.component.scss, projects/pastanaga-angular/src/lib/controls/toggles/toggles.module.ts, projects/pastanaga-angular/src/lib/dropdown/dropdown.module.ts, projects/pastanaga-angular/src/lib/dropdown/option/option.component.html, projects/pastanaga-angular/src/lib/dropdown/option/option.component.scss, projects/pastanaga-angular/src/lib/styles/_buttons.scss, projects/pastanaga-angular/src/lib/styles/_tabs.scss, projects/pastanaga-angular/src/lib/styles/theme/_button.scss, projects/pastanaga-angular/src/lib/tabs/tab-item.component.html, projects/pastanaga-angular/src/lib/tabs/tabs.module.ts
updated buttons style
only apply focus style to 
* buttons, 
* checkbox, 
* tabs 
* dropdown option 
when focus is the result of a keyboard interaction
=> button styles and keyboard-focus

CHANGELOG.md, projects/demo/src/app/demo/pages/breakpoint-page/breakpoint-page.component.ts, projects/demo/src/app/demo/pages/modal-page/dialog-example/dialog-example.component.html, projects/demo/src/app/demo/pages/modal-page/dialog-example/dialog-example.component.ts, projects/demo/src/app/demo/pages/modal-page/dialog-image-example/dialog-image-example.component.html, projects/demo/src/app/demo/pages/modal-page/dialog-image-example/dialog-image-example.component.ts, projects/demo/src/app/demo/pages/modal-page/modal-example/modal-example.component.html, projects/demo/src/app/demo/pages/modal-page/modal-example/modal-example.component.ts, projects/demo/src/app/demo/pages/modal-page/modal-page.component.html, projects/demo/src/app/demo/pages/modal-page/modal-page.component.ts, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/modal/base-modal.component.spec.ts, projects/pastanaga-angular/src/lib/modal/base-modal.component.ts, projects/pastanaga-angular/src/lib/modal/dialog/dialog.component.spec.ts, projects/pastanaga-angular/src/lib/modal/modal.model.ts, projects/pastanaga-angular/src/lib/modal/modal.service.spec.ts, projects/pastanaga-angular/src/lib/modal/modal.service.ts, projects/pastanaga-angular/src/lib/modal/modal/modal.component.spec.ts
Use DI to share data required by modal components
=> Inject modal reference

CHANGELOG.md, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/toast/toast.service.spec.ts, projects/pastanaga-angular/src/lib/toast/toast.service.ts
protect access to toast status
=> test coverage for toast service

CHANGELOG.md, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/styles/_modal.scss
=> Add bg color

CHANGELOG.md, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/common.ts, projects/pastanaga-angular/src/lib/modal/dialog/dialog.component.scss
=> adapt style of dialogs on mobile

CHANGELOG.md, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/styles/_avatar.scss, projects/pastanaga-angular/src/lib/styles/_buttons.scss
#1 [ch27969](https://app.clubhouse.io/onnahq/story/27969/hover-state-of-large-secondary-basic-button-gets-triggered-on-mobile-device)
Working as expected from what I can tell in the emulator. 
https://css-tricks.com/solving-sticky-hover-states-with-media-hover-hover/
#2 Add color for avatar initials
=> Hover state btns

CHANGELOG.md, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/tooltip/tooltip.component.html, projects/pastanaga-angular/src/lib/tooltip/tooltip.component.scss
=> Fix tooltip background color on safari

package-lock.json
Reverts plone/pastanaga-angular#452
=> Revert "Bump browserslist from 4.16.1 to 4.16.6"

CHANGELOG.md, projects/demo/src/app/app.component.ts, projects/demo/src/app/demo/demo.module.ts, projects/demo/src/app/demo/pages/avatar-page/avatar-page.component.html, projects/demo/src/app/demo/pages/dropdown-page/dropdown-page.component.html, projects/demo/src/app/demo/pages/ellipsis-tooltip-page/ellipsis-tooltip-page.component.html, projects/demo/src/app/demo/pages/ellipsis-tooltip-page/ellipsis-tooltip-page.component.scss, projects/demo/src/app/demo/pages/ellipsis-tooltip-page/ellipsis-tooltip-page.component.ts, projects/demo/src/app/demo/pages/expand-page/expander-page.component.ts, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/avatar-pile/avatar-pile.component.html, projects/pastanaga-angular/src/lib/avatar/avatar.component.ts, projects/pastanaga-angular/src/lib/avatar/avatar.model.ts, projects/pastanaga-angular/src/lib/controls/textfield/select/select.component.html, projects/pastanaga-angular/src/lib/controls/textfield/select/select.component.ts, projects/pastanaga-angular/src/lib/dropdown/dropdown.module.ts, projects/pastanaga-angular/src/lib/dropdown/option/option.component.html, projects/pastanaga-angular/src/lib/dropdown/option/option.component.scss, projects/pastanaga-angular/src/lib/popup/popup.directive.ts, projects/pastanaga-angular/src/lib/tooltip/ellipsis-tooltip.directive.spec.ts, projects/pastanaga-angular/src/lib/tooltip/ellipsis-tooltip.directive.ts, projects/pastanaga-angular/src/lib/tooltip/tootip.module.ts, projects/pastanaga-angular/src/public-api.ts
- **Ellipsis tooltip**: New Ellipsis tooltip directive
- **Avatar**: Add avatar input to avatar component
- **pa-option**: Add ellipsis tooltip on `pa-option` content and description 
- **Select**: Fix change detection to display preselected option on pa-select
=> Avatar improvement

CHANGELOG.md, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/modal/modal/modal-advanced.component.html, projects/pastanaga-angular/src/lib/styles/_modal.scss, projects/pastanaga-angular/src/lib/styles/_tables.scss
- **Modal**: Optional class for pa-modal to take all available space in height 
- `pa-lead-image` class accessible outside tables
=> Small improvements

CHANGELOG.md, projects/pastanaga/package.json, projects/pastanaga/src/lib/badge/badge.component.spec.ts, projects/pastanaga/src/lib/controls/checkbox-tree/checkbox-tree.component.spec.ts, projects/pastanaga/src/lib/translate/translate.directive.spec.ts, projects/pastanaga/src/lib/translate/translate.module.ts, projects/pastanaga/src/lib/translate/translate.pipe.ts, projects/pastanaga/src/lib/translate/translate.service.ts, projects/pastanaga/src/public_api.ts
=> Add translate service

CHANGELOG.md, projects/demo/src/app/app.module.ts, projects/demo/src/app/demo/demo.module.ts, projects/demo/src/app/demo/pages/translate-page/translate-page.component.html, projects/demo/src/app/demo/pages/translate-page/translate-page.component.scss, projects/demo/src/app/demo/pages/translate-page/translate-page.component.ts, projects/demo/src/assets/i18n/custom-fr.ts, projects/demo/src/assets/i18n/en.ts, projects/demo/src/assets/i18n/fr.ts, projects/demo/src/assets/i18n/la.ts, projects/demo/src/assets/index.ts, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/datetime/datetime.component.spec.ts, projects/pastanaga-angular/src/lib/datetime/datetime.service.spec.ts, projects/pastanaga-angular/src/lib/toast/toast.service.spec.ts, projects/pastanaga-angular/src/lib/translate/index.ts, projects/pastanaga-angular/src/lib/translate/translate.directive.spec.ts, projects/pastanaga-angular/src/lib/translate/translate.directive.ts, projects/pastanaga-angular/src/lib/translate/translate.pipe.spec.ts, projects/pastanaga-angular/src/lib/translate/translate.pipe.ts, projects/pastanaga-angular/src/lib/translate/translate.service.spec.ts, projects/pastanaga-angular/src/lib/translate/translate.service.ts, projects/pastanaga-angular/src/styles/_textfields.scss
- Fix select style
- TranslateService: Allow changing current language of the application
- Improve translate documentation
=> Change translation language dynamically

CHANGELOG.md, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/toast/toast.component.spec.ts
Checking that the Toast Component is dismissing after the proper delay
=> Added unit test to Toast Component

CHANGELOG.md, package-lock.json, package.json
=> Update @ng-web-apis/common to version 2

.github/workflows/ghpages.yml, CHANGELOG.md, projects/demo/src/app/demo/demo.module.ts, projects/demo/src/app/demo/pages/button-page/button-page.component.html, projects/demo/src/app/demo/pages/button-page/button-page.component.scss, projects/demo/src/app/demo/pages/button-page/button-usage/button-usage.component.html, projects/demo/src/app/demo/pages/button-page/button-usage/button-usage.component.ts, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/button/button.component.spec.ts, projects/pastanaga-angular/src/lib/button/button.component.ts, projects/pastanaga-angular/src/styles/_buttons.scss, projects/pastanaga-angular/src/styles/theme/_button.tokens.scss
- Update size of large button based on their padding instead of based on their line-height
- Add iconSize option on buttons
- Improve example section of button documentation page
=> Improve button theme

.github/workflows/ghpages.yml, CHANGELOG.md, README.md, angular.json, ghpages.sh, package.json, projects/demo/src/app/demo/pages/typography-page/typography-page.component.html, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/styles/_typography.scss, projects/pastanaga-angular/src/styles/theme/_typography.tokens.scss
- **Documentation**:
- improving README
- Add Table of content
- Add Setup and configuration section
- Fix outdated links and references
- moving demo to the root, so it is now accessible at https://plone.github.io/pastanaga-angular/. This should fix the routing and reloading problem.
- **Typography**: Adding tokens allowing to override Pastanaga typography rules
=> Demo and documentation

CHANGELOG.md, ghpages.sh, projects/pastanaga-angular/package.json
Don't remove .git folder when cleaning up the previous demo
=> Fix demo deployment

CHANGELOG.md, ghpages.sh, projects/pastanaga-angular/package.json
Copy the content of demo folder to dist, instead of copying demo folder itself
=> Fix demo deployment again

CHANGELOG.md, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/toast/toast.component.html, projects/pastanaga-angular/src/lib/toast/toast.component.scss, projects/pastanaga-angular/src/styles/theme/_toast.tokens.scss
- Fix text alignment in toasts without icon nor button
- Add a token allowing to change the padding when there is a button
=> Fix text alignment in toasts without icon nor button

CHANGELOG.md, projects/demo/src/app/demo/pages/button-page/button-description/button-description.component.html, projects/demo/src/app/demo/pages/button-page/button-description/button-description.component.ts, projects/demo/src/app/demo/pages/icon-page/icon-page.component.html, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/controls/textfield/index.ts, projects/pastanaga-angular/src/lib/controls/textfield/select/index.ts, projects/pastanaga-angular/src/lib/controls/textfield/text-field.module.ts, projects/pastanaga-angular/src/lib/controls/textfield/textarea/index.ts
- Fix pa-option usage with pa-select importing only PaTextFieldModule
- Improve button link documentation 
- Improve icon documentation
=> Fix pa-option usage with pa-select importing only PaTextFieldModule

CHANGELOG.md, projects/demo/src/app/demo/pages/table-page/table-row/table-row-page.component.html, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/table/table-row/table-row.component.html, projects/pastanaga-angular/src/lib/table/table-row/table-row.component.ts, projects/pastanaga-angular/src/lib/table/table.spec.ts, projects/pastanaga-angular/src/styles/components/_tables.scss, projects/pastanaga-angular/src/styles/theme/_tables.tokens.scss
- add tokens for spacing
- add transition on background color change
- add hoverable option on rows
=> Table theme improvements

CHANGELOG.md, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/controls/textfield/input/input.component.spec.ts, projects/pastanaga-angular/src/lib/controls/textfield/select/select.component.spec.ts, projects/pastanaga-angular/src/lib/controls/textfield/text-field.directive.ts, projects/pastanaga-angular/src/lib/controls/textfield/textarea/textarea.component.spec.ts, projects/pastanaga-angular/src/lib/controls/textfield/typeahead-select/typeahead-select.component.spec.ts, projects/pastanaga-angular/src/lib/modal/base-modal.component.ts, projects/pastanaga-angular/src/lib/modal/confirmation-dialog/confirmation-dialog.component.scss, projects/pastanaga-angular/src/lib/modal/modal-advanced/modal-advanced.component.html, projects/pastanaga-angular/src/lib/modal/modal-advanced/modal-advanced.component.scss, projects/pastanaga-angular/src/lib/modal/modal-advanced/modal-advanced.component.ts, projects/pastanaga-angular/src/lib/modal/modal-dialog/modal-dialog.component.html, projects/pastanaga-angular/src/lib/modal/modal-dialog/modal-dialog.component.scss, projects/pastanaga-angular/src/styles/components/_modal.scss
- **Modal advanced**: add `fitContent` option to advanced modal, when true we don't set the modal width so it fits its content width 
- **Modals**: fix modal style so the dropdowns are properly positioned in their content
- **Text fields**: increase the delay before computing label width to prevent the label to be striked by the top border
=> Modal improvements

CHANGELOG.md, projects/demo/src/app/demo/pages/date-picker-page/date-picker-page.component.html, projects/demo/src/app/demo/pages/date-picker-page/date-picker-page.component.ts, projects/demo/src/app/demo/pages/input-page/input-page.component.html, projects/demo/src/app/demo/pages/input-page/input-page.component.ts, projects/demo/src/app/demo/pages/radio-page/radio-page.component.html, projects/demo/src/app/demo/pages/radio-page/radio-page.component.ts, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/pastanaga-angular/src/lib/date-picker/date-picker.component.ts
- **date-picker**: Fix prefilled date-picker display
- **Radio documentation page**: Fix disabled radio group
=> Fix prefilled date picker

CHANGELOG.md, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/date-picker/date-picker.component.html, projects/pastanaga-angular/src/lib/date-picker/date-picker.component.ts
- Fix https://github.com/plone/pastanaga-angular/issues/657
- Add missing support for `externalLabel` option
=> Fix date format validator

CHANGELOG.md, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/controls/slider/slider.component.scss
Fix https://github.com/plone/pastanaga-angular/issues/664
=> Fix slider style (which wasn't working on webkit browsers)

CHANGELOG.md, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/date-picker/date-picker.component.ts
- **date-picker**: Fix input initialization
=> Fix date picker initialization

CHANGELOG.md, projects/demo/src/app/demo/pages/expand-page/expander-page.component.html, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/expander/expander.component.ts, projects/pastanaga-angular/src/styles/components/_expander.scss
- Fix expander style to allow having a card expander inside a "normal" expander.
- Fix `expanded` option to work on card expander (allowing to have the expander open by default also for card expander)
=> Expander improvements

CHANGELOG.md, projects/demo/src/app/demo/pages/table-page/table-cell-page/table-cell-page.component.html, projects/demo/src/app/demo/pages/table-page/table-page.component.html, projects/demo/src/app/demo/pages/table-page/table-page.component.ts, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/table/table-cell/table-cell.component.html, projects/pastanaga-angular/src/lib/table/table-cell/table-cell.component.ts, projects/pastanaga-angular/src/styles/components/_tables.scss
It allows to display a right border inside the table.
=> Add new borderRight option on table cells

CHANGELOG.md, projects/pastanaga-angular/package.json, projects/pastanaga-angular/src/lib/chips/chip-closeable/chip-closeable.component.html, projects/pastanaga-angular/src/lib/chips/chip-expandable/chip-expandable.component.html, projects/pastanaga-angular/src/lib/chips/chip-selectionable/chip-selectionable.component.html, projects/pastanaga-angular/src/lib/chips/chip/chip.component.html, projects/pastanaga-angular/src/lib/chips/chips.module.ts, projects/pastanaga-angular/src/styles/components/_chips.scss
- Display a tooltip when a chip has an ellipsis
=> Chip: display tooltip
