CHANGELOG.md
projects/pastanaga-angular/package.json
projects/pastanaga-angular/src/lib/modal/dialog/dialog.component.scss

[ch30454](https://app.clubhouse.io/onnahq/story/30454/padding-shadow-and-position-of-buttons-in-alert-dialog-don-t-currently-match-designs)

Update dialog styles

---

CHANGELOG.md
projects/pastanaga-angular/package.json
projects/pastanaga-angular/src/lib/modal/dialog/dialog.component.scss
projects/pastanaga-angular/src/lib/modal/modal/modal.component.scss

Fix for [ch37539](https://app.clubhouse.io/onnahq/story/37539/pa-dialogs-on-iphone-se-ipad-pro-are-transparent)

Add background color to pa-dialog

---

CHANGELOG.md
projects/pastanaga-angular/package.json
projects/pastanaga-angular/src/lib/controls/textfield/select/select.component.html
projects/pastanaga-angular/src/lib/popup/popup.directive.ts

Reverting some of the changes from the previous version. 
Fixes are tied to [ch39362](https://app.clubhouse.io/onnahq/story/39362/pa-dropdown-out-of-alignment-on-various-components)
Note: reverting to pastanaga version 2.17.5 also amends the issue

Dropdown fix

---

CHANGELOG.md
projects/pastanaga-angular/package.json
projects/pastanaga-angular/src/lib/styles/theme/_palette.scss

The ability to omit the units has been deprecated.  This is in prep for further removal of the deprecated node-sass.

Add units to saturation and lightness values

---

CHANGELOG.md
projects/pastanaga-angular/package.json
projects/pastanaga-angular/src/lib/styles/_chips.scss

Previous fix had a bad impact on chip look and feel when container is flex

change chip max-width to be working on mobile

---

CHANGELOG.md
projects/pastanaga-angular/package.json
projects/pastanaga-angular/src/lib/controls/textfield/input-formatter.directive.ts

This allows changes/validation to be triggered when values aren't added via keyboard (e.g., pasting via the context menu)

use `input` event instead of `keyup`

---

CHANGELOG.md
projects/pastanaga-angular/package.json
projects/pastanaga-angular/src/lib/modal/confirmation-dialog/confirmation-dialog.component.html
projects/pastanaga-angular/src/lib/modal/confirmation-dialog/confirmation-dialog.component.spec.ts

- **Confirmation dialog**: Accept HTML on confirmation dialog description 
- **Confirmation dialog**: Emit `onClose` when closing the dialog

Confirmation dialog fix and improvement

---

CHANGELOG.md
projects/pastanaga-angular/package.json
projects/pastanaga-angular/src/lib/button/button.component.spec.ts
projects/pastanaga-angular/src/lib/button/button.component.ts
projects/pastanaga-angular/src/lib/styles/_buttons.scss
projects/pastanaga-angular/src/lib/styles/theme/_button.scss

addressing new Design's requirement for small size buttons:
- Removing min-width;
- ensure that the button is 32px height;
- using small size icon for small size buttons

adjusting styling for small size buttons

---

CHANGELOG.md
projects/pastanaga-angular/package.json
projects/pastanaga-angular/src/lib/controls/textfield/select/select.component.html
projects/pastanaga-angular/src/lib/dropdown/dropdown.component.ts
projects/pastanaga-angular/src/lib/popup/popup.component.ts

- Add a new popupType `menu` so popups and menus are closed on `closeAllPopups` event, while dropdowns are not
- Set dropdown default `popupType` to `menu` instead of `dropdown`
- Update dropdown `popupType` when dropdown `role` changes

Fix popup and dropdown types

---

CHANGELOG.md
projects/pastanaga-angular/package.json
projects/pastanaga-angular/src/lib/controls/textfield/native-text-field.directive.ts

When used with a formControl using updatOn 'blur', text-field components need an early markAsDirty when the component is blurred in order to display the first validation errors

Fixed first error state not displayed after pristine using updateOn blur

---

CHANGELOG.md
projects/demo/src/app/demo/demo.module.ts
projects/demo/src/app/demo/pages/dropdown-page/dropdown-page.component.html
projects/demo/src/app/demo/pages/dropdown-page/dropdown-page.component.ts
projects/demo/src/app/demo/pages/popup-page/popup-component-usage/popup-component-usage.component.html
projects/demo/src/app/demo/pages/popup-page/popup-component-usage/popup-component-usage.component.ts
projects/demo/src/app/demo/pages/popup-page/popup-page.component.html
projects/demo/src/app/demo/pages/popup-page/popup-page.component.ts
projects/pastanaga-angular/package.json
projects/pastanaga-angular/src/lib/controls/textfield/select/select.component.html
projects/pastanaga-angular/src/lib/date-picker/date-picker.component.html
projects/pastanaga-angular/src/lib/popup/popover/popover.directive.ts
projects/pastanaga-angular/src/lib/popup/popup.component.ts
projects/pastanaga-angular/src/lib/popup/popup.directive.ts

- **Popup directive**: 
- rename `popupOnRight` into `alignPopupOnLeft` to align the attribute name with its behavior
- rename `popupMargin` into `popupVerticalOffset` to align the attribute name with its behavior
- implement `popupOnRight` with a behavior aligned to its name: when true the popup is positioned on the right of the directive element
- CSS position is now fixed instead of absolute 
- **Popup**: 
- Add documentation for `popupOffset` attribute
- **Dropdown**: 
- Fix and document multi-level dropdown demo (`keepOthersOpen` attribute was missing)
- Add popup usage section in dropdown usage
- Improve global look and feel of dropdown documentation page

Dropdown and Popup improvements

---

CHANGELOG.md
package-lock.json
projects/demo/src/app/demo/pages/form-control-page/usage/pa-form-control-usage.component.html
projects/demo/src/app/demo/pages/input-page/input-page.component.html
projects/demo/src/app/demo/pages/toggle-page/toggle-page.component.html
projects/demo/src/app/demo/pages/toggle-page/toggle-page.component.ts
projects/pastanaga-angular/package.json
projects/pastanaga-angular/src/lib/controls/textfield/index.ts
projects/pastanaga-angular/src/lib/controls/textfield/input/input.component.html
projects/pastanaga-angular/src/lib/controls/textfield/input/input.component.spec.ts
projects/pastanaga-angular/src/lib/controls/textfield/native-text-field.directive.ts
projects/pastanaga-angular/src/lib/controls/textfield/select/select.component.html
projects/pastanaga-angular/src/lib/controls/textfield/select/select.component.spec.ts
projects/pastanaga-angular/src/lib/controls/textfield/select/select.component.ts
projects/pastanaga-angular/src/lib/controls/textfield/text-field.directive.ts
projects/pastanaga-angular/src/lib/controls/textfield/text-field.module.ts
projects/pastanaga-angular/src/lib/controls/textfield/textarea/textarea.component.html
projects/pastanaga-angular/src/lib/controls/textfield/textarea/textarea.component.spec.ts
projects/pastanaga-angular/src/lib/controls/toggles/toggle/toggle.component.html
projects/pastanaga-angular/src/lib/controls/toggles/toggle/toggle.component.scss
projects/pastanaga-angular/src/lib/controls/toggles/toggle/toggle.component.spec.ts
projects/pastanaga-angular/src/lib/controls/toggles/toggle/toggle.component.ts
projects/pastanaga-angular/src/styles/_checkbox.scss
projects/pastanaga-angular/src/styles/_select.scss
projects/pastanaga-angular/src/styles/_textfields.scss
projects/pastanaga-angular/src/styles/theme/_spacing.tokens.scss
projects/pastanaga-angular/src/styles/theme/_textfield.tokens.scss
projects/pastanaga-angular/src/styles/theme/_typography.tokens.scss

- Text fields: 
- No more background color on text fields by default
- Improve text field border so label doesn't require a background color and border keep space for the label on active and focus states
- Replace border-text-field tokens by border-color-text-field token
- Text field borders management:
- No more borders on input themselves
- Add a new `pa-field-container` carrying the classes for all the states (error, disabled, readonly, focus, has content)
- No more background required on labels to have them displayed over the top border
- Replace border-text-field tokens by border-color-text-field tokens
- Use this new style structure on all our fields (input, textarea, select)
- New `TextFieldDirective` managing label width as well as focus and content states
- Update label position …

Text field improvements

---

CHANGELOG.md
package-lock.json
projects/pastanaga-angular/package.json
projects/pastanaga-angular/src/lib/table/table-sortable-header-cell/table-sortable-header-cell.component.ts

- Fix `table-sortable-header-cell` component to update the icon when `enabled` changes
- Bump http-cache-semantics from 4.1.0 to 4.1.1

Fix sortable table header icon

---

CHANGELOG.md
projects/demo/src/app/demo/pages/table-page/table-cell-page/table-cell-page.component.html
projects/demo/src/app/demo/pages/table-page/table-sortable-header-page/table-sortable-header-page.component.html
projects/demo/src/app/demo/pages/table-page/table-sortable-header-page/table-sortable-header-page.component.ts
projects/pastanaga-angular/package.json
projects/pastanaga-angular/src/lib/table/table-cell/table-cell.component.html
projects/pastanaga-angular/src/lib/table/table-cell/table-cell.component.ts
projects/pastanaga-angular/src/lib/table/table-sortable-header-cell/table-sortable-header-cell.component.html
projects/pastanaga-angular/src/lib/table/table-sortable-header-cell/table-sortable-header-cell.component.scss
projects/pastanaga-angular/src/lib/table/table-sortable-header-cell/table-sortable-header-cell.component.ts
projects/pastanaga-angular/src/lib/table/table-sortable-header/table-sortable-header.component.html
projects/pastanaga-angular/src/lib/table/table.component.ts
projects/pastanaga-angular/src/lib/table/table.models.ts
projects/pastanaga-angular/src/styles/components/_tables.scss

- add center option to table cells
- tokenize text-transform on header cells
- add `ng-content` on `table-sortable-header` allowing the addition of free content on first column. This is specially useful when we want to have a first column made of checkboxes for instance.

Table improvements

---

CHANGELOG.md
projects/demo/src/app/demo/pages/tooltip-page/tooltip-page.component.html
projects/pastanaga-angular/package.json
projects/pastanaga-angular/src/lib/modal/modal.service.ts
projects/pastanaga-angular/src/lib/toast/toast.service.spec.ts
projects/pastanaga-angular/src/lib/toast/toast.service.ts
projects/pastanaga-angular/src/lib/tooltip/tooltip.directive.ts
projects/pastanaga-angular/src/styles/components/_toast.scss

- Fix https://github.com/plone/pastanaga-angular/issues/600 : Replace deprecated ComponentFactoryResolver
- Toast improvements:   
- Prevent toast container to capture clicks 
- Add ability to close toasts by pressing escape

Replace deprecated ComponentFactoryResolver + Toast improvements

---

CHANGELOG.md
projects/demo/src/app/demo/pages/ellipsis-tooltip-page/ellipsis-tooltip-page.component.html
projects/demo/src/app/demo/pages/select-page/select-page.component.html
projects/pastanaga-angular/package.json
projects/pastanaga-angular/src/lib/controls/textfield/select/select.component.html
projects/pastanaga-angular/src/lib/controls/textfield/select/select.component.spec.ts
projects/pastanaga-angular/src/lib/controls/textfield/text-field.module.ts
projects/pastanaga-angular/src/lib/controls/textfield/typeahead-select/typeahead-select.component.spec.ts
projects/pastanaga-angular/src/lib/dropdown/option/option.component.html
projects/pastanaga-angular/src/lib/dropdown/option/option.component.scss
projects/pastanaga-angular/src/lib/dropdown/option/option.component.ts
projects/pastanaga-angular/src/lib/tooltip/ellipsis-tooltip.directive.spec.ts
projects/pastanaga-angular/src/lib/tooltip/ellipsis-tooltip.directive.ts

- **paEllipsisTooltip**: Rename `content` attribute to `paEllipsisContent`
- **Select**: Use `paEllipsisTooltip` and `paEllipsisContent` to properly display long selected value
- **Option**: Use `paEllipsisContent` to properly display the tooltip on hover when the option has an ellipsis

Use paEllipsisTooltip in paSelect and paOption

---

CHANGELOG.md
projects/demo/src/app/demo/pages/dropdown-page/dropdown-page.component.html
projects/demo/src/app/demo/pages/dropdown-page/dropdown-page.component.ts
projects/demo/src/app/demo/pages/icon-page/base-icon-page.component.ts
projects/demo/src/app/demo/pages/icon-page/icon-page.component.html
projects/demo/src/app/demo/pages/popup-page/popup-page.component.html
projects/pastanaga-angular/package.json
projects/pastanaga-angular/src/lib/common.ts
projects/pastanaga-angular/src/lib/icon/icon.component.ts
projects/pastanaga-angular/src/lib/popup/popup.directive.ts

- **Icons**: New `SPRITE_CACHE_VERSION` injection token allowing to manage the cache version of svg sprite
- **Popup**: Fix popup position when one of the popup’s parent has `container-type: size`

Cache management on glyphs sprite + fix popup position for container-type: size

---

CHANGELOG.md
projects/demo/src/app/demo/pages/dropdown-page/dropdown-page.component.html
projects/demo/src/app/demo/pages/dropdown-page/dropdown-page.component.ts
projects/demo/src/app/demo/pages/ellipsis-tooltip-page/ellipsis-tooltip-page.component.html
projects/demo/src/assets/i18n/en.ts
projects/pastanaga-angular/package.json
projects/pastanaga-angular/src/lib/common.ts
projects/pastanaga-angular/src/lib/controls/textfield/select/select.component.spec.ts
projects/pastanaga-angular/src/lib/controls/textfield/typeahead-select/typeahead-select.component.spec.ts
projects/pastanaga-angular/src/lib/controls/toggles/checkbox/checkbox.component.html
projects/pastanaga-angular/src/lib/controls/toggles/toggles.module.ts
projects/pastanaga-angular/src/lib/dropdown/dropdown.component.html
projects/pastanaga-angular/src/lib/dropdown/option/option.component.ts
projects/pastanaga-angular/src/lib/modal/modal-advanced/modal-advanced.component.spec.ts
projects/pastanaga-angular/src/lib/popup/popup.directive.ts
projects/pastanaga-angular/src/lib/tooltip/ellipsis-tooltip.directive.spec.ts
projects/pastanaga-angular/src/lib/tooltip/ellipsis-tooltip.directive.ts
projects/pastanaga-angular/src/lib/tooltip/tooltip.component.ts
projects/pastanaga-angular/src/lib/tooltip/tooltip.directive.ts
setup-jest.ts

- **Tooltip**:
- Fix tooltip position when directive parent has `container-type: size`
- Display tooltip from dropdown option on the first hover event
- Prevent tooltip content to be duplicated
- **Ellipsis Tooltip**:
- Update ellipsis tooltip in options when dropdown is displayed
- Add `noEllipsis` option to disable the ellipsis tooltip if needed: we cannot optionally add ellipsis tooltip directive,
but in some components like checkbox, we need the ability to display an ellipsis or not.
`noEllipsis` option allows to use `paEllipsisTooltip` and optionally disable it.    
- **Checkbox**: Display a tooltip when the label has en ellipsis

Fix tooltip in options

---

CHANGELOG.md
projects/pastanaga-angular/package.json
projects/pastanaga-angular/src/lib/controls/form-field/pa-form-control.directive.ts

when a field was programmatically disabled while the focus was in, the field still had the focus state (even though it didn't have the focus) when the field was then enabled again.
To prevent this bug, we now call `blur` on the field on `setDisableState` method.

Call blur when disabling a field

---

CHANGELOG.md
projects/demo/src/app/demo/pages/modal-page/modal-example/modal-example.component.html
projects/pastanaga-angular/package.json
projects/pastanaga-angular/src/lib/common.ts
projects/pastanaga-angular/src/lib/dropdown/dropdown.component.ts
projects/pastanaga-angular/src/lib/popup/popup.component.ts

when the dropdown is included in a container with `position: fixed` (like in a modal for instance), and in a scrollable container, we automatically close the dropdown on scroll event to prevent the dropdown to move while scrolling.

Close dropdown on scroll in position fixed container

---

CHANGELOG.md
projects/demo/src/app/demo/pages/input-page/input-page.component.html
projects/pastanaga-angular/package.json
projects/pastanaga-angular/src/lib/controls/textfield/input-formatter.directive.ts
projects/pastanaga-angular/src/lib/controls/textfield/input/input.component.html
projects/pastanaga-angular/src/lib/controls/textfield/input/input.component.ts

* Support input native `step` attribute
* Support entering decimal numbers via keyboard when input type is `number`

Input: improve inputs of type number
